### ISSUE TITLE
Extension No Longer Working

### ISSUE THREAD

**Issue by ThatGuyAgain42** [zopieux/spotify-now-playing-chrome-extension#1]
Line 66 of content.js returns null
This should be fixed by simply changing the query CSS selector to just `"[role=contentinfo]"` ?
The original line of code: `document.querySelector("div.now-playing-widget[role=contentinfo]");` is broken by the div class no longer being of the `"now-playing-widget"` class

**Comment by zopieux** [comment]
Thanks for reporting, I'll have a look later.

**Comment by zopieux** [comment]
Thanks, issue is fixed. v0.1.2 is pending Chrome Web Store review.
